title: inż Tomasz Kowalczyk
description: 
baseurl: ""
url: "https://janzbedny.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

menu:
  - title: Dane osobowe
    url: /
  - title: Wykształcenie
    url: /about.md
  - title: Doświadczenie zawodowe
    url: /experience.md
