title: in≈º Tomasz Kowalczyk
description: Strona O Mnie.
baseurl: ""
url: "https://janzbedny.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

menu:
  - title: O Mnie
    url: /
  - title: O mnie
    url: /about.md
  - title: Blog
    url: /blog/
